# Generated by Django 4.2.1 on 2023-05-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0002_delete_entregable_curso_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='creador',
        ),
    ]
